force-app/main/default/objects/Contact/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Program_Name__c</fullName>
    <label>Current Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactTriggerHandler.cls
public class ContactTriggerHandler extends TriggerHandler{

    private List<Id> programIds = new List<Id>();
    private Map <ID,Program__c> programNames = new Map<ID,Program__c>();

    public ContactTriggerHandler() {
        for (Contact i : (List<Contact>)Trigger.New){
            programIds.add(i.Current_Program__c);
        }
        programNames.putAll([SELECT Id, Name FROM Program__c WHERE Id IN :programIds]);

    }
    
    public override void beforeInsert(){
        insertProgramNameField();
    }

    public override void beforeUpdate(){
        updatePragramNameField();
    }
    
    public void insertProgramNameField(){
        for(Contact con : (List<Contact>)Trigger.New){
            con.Current_Program_Name__c = programNames.get(con.Current_Program__c).name;
        }
    }

    public void updatePragramNameField(){
        for (Contact con : (List<Contact>)Trigger.New){
            if(((Contact)trigger.oldMap.get(con.Id)).Current_Program__c != con.Current_Program__c){
                con.Current_Program_Name__c = programNames.get(con.Current_Program__c).name;
            }
        }
    }
}




        