force-app/main/default/objects/Contact/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Program_Name__c</fullName>
    <label>Current Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactTriggerTest.cls
@isTest
public with sharing class ContactTriggerTest {
    @isTest
    public static void ContactTriggerTestInsert() {
        
        List<Program__c> progs = new List<Program__c>();
        for(Integer i =100; i < 301; i++){
            progs.add(new program__c(Name = 'test' + i));
        }
        insert progs;
        Test.startTest();
        List<Contact> cons = new List<Contact>();
        for(Integer i =100; i < 301; i++){
            cons.add(new Contact(LastName = '' + i, Current_Program__c = progs[i-100].id));
        }
        insert cons;
        Test.stopTest();
        
        List<Contact> consEnd = new List<Contact>([SELECT name, Current_Program_Name__c FROM Contact ORDER BY name]);
        System.debug(consEnd);
        Integer i = 100;
        for(Contact con :consEnd){
            System.debug('test' + i + '==>' + con.Current_Program_Name__c);
            System.assertEquals('test' + i, con.Current_Program_Name__c);
            i++;
        }

    }
    @isTest
    public static void ContactTriggerTestUpdate() {
        
        List<Program__c> progs = new List<Program__c>();
        for(Integer i =0; i < 200; i++){
            progs.add(new program__c(name = 'test' +i));
        }
        insert progs;
        List<Contact> cons = new List<Contact>();
        for(Integer i =0; i < 200; i++){
            cons.add(new Contact(LastName = 'test' + i, Current_Program__c = progs[i].id));
        }
        insert cons;
        Test.startTest();
        List<Contact> consAfterInsert = [SELECT name, Current_Program__c FROM Contact ORDER BY name];
        for(Integer i = 0; i < 200; i++){
            consAfterInsert[i].Current_Program__c = progs[199-i].id;
            
        }
        update consAfterInsert;
        Test.stopTest();
        List<Contact> consEnd = new List<Contact>([SELECT name, Current_Program_Name__c FROM Contact ORDER BY name]);
        System.debug(consEnd);
        Integer i = consEnd.size();
        for(Contact con :consEnd){
            System.debug('test' + (i-1) + '==>' + con.Current_Program_Name__c);
            System.assertEquals('test' + (i-1), con.Current_Program_Name__c);
            i--;
        }   
    }
}