force-app/main/default/objects/Contact/fields/Current_Program__c.field-meta.xml
<CustomField>
    <fullName>Current_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Program_Name__c</fullName>
    <label>Current Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactTroggerHandler.cls
public class ContactTroggerHandler extends TriggerHandler{

    private list<id> programIds = new list<id>();
    private Map <ID,Program__c> names = new Map<ID,Program__c>();

    public ContactTroggerHandler() {
        for (Contact i : (List<Contact>)Trigger.New){
            programIds.add(i.Current_Program__c);
        }
        names.putAll([SELECT id, name FROM Program__c WHERE id IN :programIds]);

    }

    public override void beforeInsert(){
        for(Contact con : (List<Contact>)Trigger.New){
            con.Current_Program_Name__c = names.get(con.Current_Program__c).name;
        }
    }

    public override void beforeUpdate(){
        for (Contact con : (List<Contact>)Trigger.New){
            //Contact con = (Contact)Trigger.oldMap.get(i.id);
            //System.debug(con.Current_Program__c + ' => ' + i.id);
            if(((Contact)trigger.oldMap.get(con.id)).Current_Program__c != con.Current_Program__c){
                con.Current_Program_Name__c = names.get(con.Current_Program__c).name;
            }
        }
    }
}